# Generated by Django 6.0.2 on 2026-02-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_fileuploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_of_sale',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_sale_vlue',
        ),
    ]
